# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 14:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.SmallIntegerField(choices=[(0, 'stage default'), (1, 'stage 1: personal'), (2, 'stage 2: team'), (3, 'stage 3: results')], default=0)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='answer time')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='choice text')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('factor', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='correctness factor from 0 to 1')),
            ],
            options={
                'ordering': ['question', 'priority', 'id'],
                'verbose_name': 'question answer choice',
                'verbose_name_plural': 'question answer choices',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('status', models.SmallIntegerField(choices=[(0, 'draft'), (1, 'new game'), (2, 'game in progress'), (3, 'game completed')], default=0, verbose_name='game status')),
                ('stage', models.SmallIntegerField(choices=[(0, 'stage default'), (1, 'stage 1: personal'), (2, 'stage 2: team'), (3, 'stage 3: results')], default=0, verbose_name='game stage')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='password to join')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0430\u043a\u0442\u0438\u0432\u0435\u043d')),
            ],
            options={
                'ordering': ('team',),
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question text')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Game', verbose_name='game')),
            ],
            options={
                'ordering': ['game', 'priority', 'id'],
                'verbose_name': '\u0432\u043e\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u0432\u043e\u043f\u0440\u043e\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='team name')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Game', verbose_name='game')),
            ],
            options={
                'ordering': ('game', 'priority', 'name'),
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='with_questions', to='core.Question', verbose_name='current question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('team', 'user')]),
        ),
    ]
